add support for bearer tokens in websocket protocols
projectcapsule/capsule-proxy pull request #533
Opened 2024-09-30 03:50 UTC by CrimsonFez

This is a simple change that enables us to extract the JWT from the WebSocket protocols as defined here https://github.com/kubernetes/kubernetes/pull/47740. This satisfies #499.

Let me know if any changes are needed.

Thank you!

2024-10-07 14:13 UTC, oliverbaehler commented
HI! You need to sign off your commits and gpg sign them as well :)

2024-10-07 17:25 UTC, CrimsonFez commented
Should now be correct

2024-10-08 08:45 UTC, prometherion requested changes
Maybe the suggested code is incorrect, but we cannot return an empty token, otherwise the following calls would inherit the capsule-proxy one leading to a potential privilege escalation.

2024-10-08 08:45 UTC, prometherion commented on internal/request/http.go
> +	}
```suggestion
	switch {
	case tradBearer != "":
		return tradBearer
	case wsHeader != "":
		re := regexp.MustCompile(`(base64url\.bearer\.authorization\.k8s\.io\.)([^,]*)`)
		match := re.FindStringSubmatch(wsHeader)
		if len(match) <= 3 {
			panic("token for was doesn't match regex")
		}
		// our token is base64 encoded without padding
		b64decode, err := base64.RawStdEncoding.DecodeString(match[2])
		if err != nil {
			panic(fmt.Sprintf("failed to decode websocket auth bearer: %s", err.Error()))
		}
		if match[2] == "" {
			panic("missing token from ws")
		}

		return string(b64decode)
	default:
		panic("cannot retrieve token from Bearer or Sec-Websocket-Protocol headers")
	}
```

2024-10-08 12:11 UTC, CrimsonFez commented
You have a good point. 
However, I believe that later parts of the code check if the token string is empty and return an error stating that we cannot authenticate anonymous users.

2024-10-10 15:30 UTC, prometherion commented
@CrimsonFez you're right, touché!

Given the increased complexity it would be good if we could return an error and make it visible in the logs: we can achieve that with `panic` which is not ideal per se, or rather, by returning a second return such as the `error`.

2024-11-04 09:55 UTC, prometherion requested changes
LGTM, happy to get this merged, just ensure the changes comply with the linters:

```
make golint
```

2024-11-11 20:23 UTC, prometherion approved these changes
Super happy getting this merged, thanks a lot! 🚀

2024-11-11 20:24 UTC, prometherion commented
Ah, `golangci-lint` complains about minor style stuff: this should be the latest round, please @CrimsonFez, may I ask you to amend it?

You can test with `golangci-lint` by issuing `make golint`

2024-11-11 20:28 UTC, CrimsonFez commented
Sure thing. I thought I got it all ;(

2024-11-14 13:47 UTC, merged

2024-11-14 19:18 UTC, CrimsonFez commented
Thanks for cleaning that up! I don't always have a lot of time to do stuff. Very much appreciated!

2024-11-14 19:19 UTC, prometherion commented
It's team work, thanks, mate!

On Thu, Nov 14, 2024, 20:19 CrimsonFez ***@***.***> wrote:

> Thanks for cleaning that up! I don't always have a lot of time to do
> stuff. Very much appreciated!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/projectcapsule/capsule-proxy/pull/533#issuecomment-2477225929>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJ7S3QWGKNQ2EID52MI3Q32ATZSTAVCNFSM6AAAAABPCMEBZOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZXGIZDKOJSHE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>